[project]
name = "natsune"
version = "0.1.0"
description = "Higher Order Concurrency in python"
requires-python = ">=3.14"
authors = [{ name = "Zachary Collins", email = "recursive.cookie.jar@gmail.com" }]
license = { text = "Apache-2" }
dependencies = [
]

[project.scripts]

[project.optional-dependencies]
dev = [
    "ty>=0.0.49",
    "black>=26.5.1",
    "pytest>=9.1.1",
    "pre-commit>=4.0.0",
    "karakuri>=0.1.0"
]

[build-system]
requires = ["hatchling", "editables"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel.force-include]
[tool.uv.sources]
karakuri = { editable = true, path = "/Users/zach/karakuri" }

[tool.hatch.build.targets.wheel]
packages = ["src/natsune"]

[dependency-groups]
dev = []

# Black code formatter configuration
[tool.black]
line-length = 88
target-version = ["py314"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
    | \.venv
    | build
    | dist
)/
'''

# pytest configuration
[tool.pytest.ini_options]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "-v --tb=short"
testpaths = ["tests", "src"]
