"""The IR: nodes, builder, and renderer (COMPILER_REFACTOR.md §3–§4)."""

from natsune.frontend.ir.builder import build_ir
from natsune.frontend.ir.nodes import (
    IrAssign,
    IrAugAssign,
    IrBody,
    IrBoolOp,
    IrBreak,
    IrCallInet,
    IrConst,
    IrContinue,
    IrDynamic,
    IrExpr,
    IrExprStmt,
    IrFor,
    IrFunction,
    IrIf,
    IrNode,
    IrParIndex,
    IrReturn,
    IrStmt,
    IrTarget,
    IrTargetDynamic,
    IrTargetName,
    IrTargetTuple,
    IrTuple,
    IrVar,
    IrWhile,
)
from natsune.frontend.ir.render import render_adapter, render_function

__all__ = [
    "IrAssign",
    "IrAugAssign",
    "IrBody",
    "IrBoolOp",
    "IrBreak",
    "IrCallInet",
    "IrConst",
    "IrContinue",
    "IrDynamic",
    "IrExpr",
    "IrExprStmt",
    "IrFor",
    "IrFunction",
    "IrIf",
    "IrNode",
    "IrParIndex",
    "IrReturn",
    "IrStmt",
    "IrTarget",
    "IrTargetDynamic",
    "IrTargetName",
    "IrTargetTuple",
    "IrTuple",
    "IrVar",
    "IrWhile",
    "build_ir",
    "render_adapter",
    "render_function",
]
