"""The IR: nodes, builder, and renderer."""

from natsune.frontend.ir.builder import build_ir
from natsune.frontend.ir.nodes import (
    Exits,
    IrAssign,
    IrAugAssign,
    IrBody,
    IrBodyExit,
    IrBoolOp,
    IrBreak,
    IrCallInet,
    IrConst,
    IrContinue,
    IrDynamic,
    IrExpr,
    IrExprStmt,
    IrFor,
    IrFunction,
    IrIf,
    IrNode,
    IrParIndex,
    IrReturn,
    IrStmt,
    IrStructureError,
    IrTarget,
    IrTargetDynamic,
    IrTargetName,
    IrTargetTuple,
    IrTuple,
    IrVar,
    IrWhile,
    VariableUsage,
    analyze_ir_body,
    iter_child_expressions,
)
from natsune.frontend.ir.render import render_adapter, render_function

__all__ = [
    "Exits",
    "IrAssign",
    "IrAugAssign",
    "IrBody",
    "IrBodyExit",
    "IrBoolOp",
    "IrBreak",
    "IrCallInet",
    "IrConst",
    "IrContinue",
    "IrDynamic",
    "IrExpr",
    "IrExprStmt",
    "IrFor",
    "IrFunction",
    "IrIf",
    "IrNode",
    "IrParIndex",
    "IrReturn",
    "IrStmt",
    "IrStructureError",
    "IrTarget",
    "IrTargetDynamic",
    "IrTargetName",
    "IrTargetTuple",
    "IrTuple",
    "IrVar",
    "IrWhile",
    "VariableUsage",
    "analyze_ir_body",
    "iter_child_expressions",
    "build_ir",
    "render_adapter",
    "render_function",
]
